app/models/cost_center.py
from app import db
from flask import current_app
import requests
from sqlalchemy import Column, Integer, text

class CostCenter(db.Model):
    __tablename__ = 'cost_center'
    
    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String(300), index= True, unique=True)
    name = db.Column(db.String(64), index=True , unique=True)
    id_number = db.Column(db.Integer, unique=True)
    branch = db.Column(db.String(300))
    location = db.Column(db.String(300) , nullable=True)
    management=db.Column(db.String(300))
    manager = db.Column(db.String(300))
    email_manager = db.Column(db.String(120))
    administrator = db.Column(db.String(300))
    administrator_email = db.Column(db.String(300))
    administrator_cellphone = db.Column(db.String(16))
    active = db.Column(db.Integer , server_default=text("1"))

    def __repr__(self):
        return f'<Cost Center {self.name} {self.id_number}>'
    
     # Flask-Login requiere estos métodos:
    def get_id(self):
        return str(self.uuid)
    
    @property
    def is_active(self):
        return self.active
    
    

app/routes/cost_center_routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, send_file
from flask_login import login_required
from app import db
from app.models import CostCenter
from app.utils.cost_center_forms import CostCenterForm
import pandas as pd
import uuid
from openpyxl import load_workbook
from io import BytesIO

bp = Blueprint('cost_center', __name__, url_prefix='/cost_center')

# Ruta para listar todos los Centro Costo
@bp.route('/list')
@login_required
def list_cost_center():
    cost_centers = CostCenter.query.filter_by(active=1).all()  # Obtener todos los Centro Costo
    return render_template('cost_center/list.html', cost_centers=cost_centers)

# Ruta para ver los detalles de un centro_costo
@bp.route('/<int:cost_center_id>/details')
@login_required
def cost_center_details(cost_center_id):
    cost_center = CostCenter.query.get_or_404(cost_center_id)  # Obtener el centro_costo por su ID
    return render_template('cost_center/details.html', cost_center=cost_center)

# Ruta para crear un nuevo centro_costo
@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_cost_center():
    form = CostCenterForm()

    if form.validate_on_submit():
        # Crear un nuevo centro_costo
        cost_center = CostCenter(
            name=form.name.data,
            branch=form.branch.data,
            location=form.location.data,
            id_number=form.id_number.data,
            management=form.management.data,
            manager=form.manager.data,
            email_manager=form.email_manager.data,
            administrator=form.administrator.data,
            administrator_email=form.administrator_email.data,
            administrator_cellphone=form.administrator_cellphone.data,
        )
        db.session.add(cost_center)
        db.session.commit()
        flash('centro_costo creado exitosamente!', 'success')
        return redirect(url_for('cost_center.list_cost_centers'))

    return render_template('cost_center/create.html', form=form)




@bp.route('/upload-cost-center', methods=['POST'])
def upload_cost_centers():
    archivo = request.files.get('archivo')
    if not archivo or not archivo.filename.endswith('.xlsx'):
        flash('Por favor, sube un archivo .xlsx válido.', 'warning')
        return redirect(url_for('cost_center.list_cost_center'))
    try:
         # Verificamos que sea un archivo Excel válido con openpyxl
        workbook = load_workbook(filename=BytesIO(archivo.read()))
        archivo.seek(0)  # Reiniciamos el puntero para que pandas pueda leer el archivo también
        df = pd.read_excel(archivo)
        columnas_requeridas = {"CC", "NOMBRE-CC", "Sucursal", "Faena", "Gerencia","Gerente", "Correo-Gerente", "Administrador", "Correo-Administrador", "Celular-Administrador"}
        if not columnas_requeridas.issubset(df.columns):
            faltantes = columnas_requeridas - set(df.columns)
            flash(f'Faltan columnas requeridas: {", ".join(faltantes)}', 'danger')
            return redirect(url_for('cost_center.list_cost_center'))
        for _, row in df.iterrows():
            nuevo_centro_costo = CostCenter(
                uuid=str(uuid.uuid4()),
                id_number=row['CC'],
                name=row['NOMBRE-CC'],
                branch=row['Sucursal'],
                location=row['Faena'],
                management=row['Gerencia'],
                manager=row['Gerente'],
                email_manager=row['Correo-Gerente'],
                administrator=row['Administrador'],
                administrator_email=row['Correo-Administrador'],
                administrator_cellphone=row['Celular-Administrador'],
            )
            db.session.add(nuevo_centro_costo)
        db.session.commit()
        flash('Centro Costo cargados correctamente.', 'success')
    except Exception as e:
            flash(f'Error al procesar el archivo: {e}', 'danger')
    return redirect(url_for('cost_center.list_cost_center'))

@bp.route('/cost_centers/download', methods=['GET'])
def download_cost_centers_excel():
    cost_centers = CostCenter.query.all()

    data = [{
        "CC": cc.code,
        "NOMBRE-CC": cc.name,
        "Sucursal": cc.branch,
        "Faena": cc.site,
        "Gerencia": cc.management,
        "Gerente": cc.manager,
        "Correo-Gerente": cc.manager_email,
        "Administrador": cc.admin,
        "Correo-Administrador": cc.admin_email,
        "Celular-Administrador": cc.admin_phone,
    } for cc in cost_centers]

    df = pd.DataFrame(data)

    output = BytesIO()
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        df.to_excel(writer, index=False, sheet_name='CostCenters')

    output.seek(0)

    return send_file(output,
                     as_attachment=True,
                     download_name="cost_centers.xlsx",
                     mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

app/routes/customer_routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, send_file
from flask_login import login_required
from app import db
from app.models import Customer
from app.utils.customer_forms import CustomerForm
import pandas as pd
import uuid
from openpyxl import load_workbook
from io import BytesIO

bp = Blueprint('customer', __name__, url_prefix='/customer')

# Ruta para listar todos los clientes
@bp.route('/list')
@login_required
def list_customers():
    customers = Customer.query.filter_by(active=1).all()  # Obtener todos los clientes
    return render_template('customer/list.html', customers=customers)

# Ruta para ver los detalles de un cliente
@bp.route('/<int:customer_id>/details')
@login_required
def customer_details(customer_id):
    customer = Customer.query.get_or_404(customer_id)  # Obtener el cliente por su ID
    return render_template('customer/details.html', customer=customer)

# Ruta para crear un nuevo cliente
@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_customer():
    form = CustomerForm()

    if form.validate_on_submit():
        # Crear un nuevo cliente
        customer = Customer(
            name=form.name.data,
            email=form.email.data,
            phone=form.phone.data,
            address=form.address.data
        )
        db.session.add(customer)
        db.session.commit()
        flash('Cliente creado exitosamente!', 'success')
        return redirect(url_for('customer.list_customers'))

    return render_template('customer/create.html', form=form)


@bp.route('/list/upgrade')
@login_required
def list_upgrade_customers():
    #customers = Customer.query.all()  # Obtener todos los clientes
    customer = Customer()
    customers = customer.get_all_users()
    return customers
    return render_template('customer/list.html', customers=customers)


@bp.route('/upload-customers', methods=['POST'])
def upload_customers():
    archivo = request.files.get('archivo')
    if not archivo or not archivo.filename.endswith('.xlsx'):
        flash('Por favor, sube un archivo .xlsx válido.', 'warning')
        return redirect(url_for('customer.list_customers'))
    try:
         # Verificamos que sea un archivo Excel válido con openpyxl
        workbook = load_workbook(filename=BytesIO(archivo.read()))
        archivo.seek(0)  # Reiniciamos el puntero para que pandas pueda leer el archivo también
        df = pd.read_excel(archivo)
        columnas_requeridas = {"Nombre", "Apellido", "Rut", "Centro-Costo", "Cargo", "Email"}
        if not columnas_requeridas.issubset(df.columns):
            faltantes = columnas_requeridas - set(df.columns)
            flash(f'Faltan columnas requeridas: {", ".join(faltantes)}', 'danger')
            return redirect(url_for('customer.list_customers'))
        for _, row in df.iterrows():
            nuevo_cliente = Customer(
                uuid=str(uuid.uuid4()),
                name=row['Nombre'],
                lastname=row['Apellido'],
                id_number=row['Rut'],
                cost_center=row['Centro-Costo'],
                job_title=row['Cargo'],
                email=row['Email']
            )
            db.session.add(nuevo_cliente)
        db.session.commit()
        flash('Clientes cargados correctamente.', 'success')
    except Exception as e:
            flash(f'Error al procesar el archivo: {e}', 'danger')
    return redirect(url_for('customer.list_customers'))


@bp.route('/customers/download', methods=['GET'])
def download_customers_excel():
    customers = Customer.query.all()

    data = [{
        "RUT": c.id_number,
        "Nombre": f"{c.name} {c.lastname}",
        "CC": c.cost_center,
        "Cargo": c.job_title,
        "Email": c.email
    } for c in customers]

    df = pd.DataFrame(data)

    output = BytesIO()
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        df.to_excel(writer, index=False, sheet_name='Trabajadores')

    output.seek(0)

    return send_file(output,
                     as_attachment=True,
                     download_name="trabajadores.xlsx",
                     mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

app/templates/cost_center/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Crear Nuevo Cliente</h2>

        <form method="POST" action="{{ url_for('customer.create_customer') }}">
            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {{ form.name(class="form-control") }}
            </div>

            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control") }}
            </div>

            <div class="form-group">
                {{ form.phone.label(class="form-control-label") }}
                {{ form.phone(class="form-control") }}
            </div>

            <div class="form-group">
                {{ form.address.label(class="form-control-label") }}
                {{ form.address(class="form-control") }}
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Crear Cliente</button>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/cost_center/details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Detalles del Cliente: {{ cost_center.name }}</h2>

        <ul class="list-group">
            <li class="list-group-item"><strong>UUID:</strong> {{ cost_center.uuid }}</li>
            <li class="list-group-item"><strong>CC:</strong> {{ cost_center.id_number }}</li>
            <li class="list-group-item"><strong>Nombre:</strong> {{ cost_center.name }}</li>
            <li class="list-group-item"><strong>Gerencia:</strong> {{ cost_center.management }}</li>
            <li class="list-group-item"><strong>Gerente:</strong> {{ cost_center.manager }}</li>
            <li class="list-group-item"><strong>Email Gerente:</strong> {{ cost_center.manager_email }}</li>
            <li class="list-group-item"><strong>Administrador:</strong> {{ cost_center.administrator }}</li>
            <li class="list-group-item"><strong>Email Administrador:</strong> {{ cost_center.administrator_email }}</li>
            <li class="list-group-item"><strong>Celular Administrador:</strong> {{ cost_center.administrator_cellphone }}</li>
            <li class="list-group-item"><strong>Active:</strong> {{ cost_center.active }}</li>
        </ul>

        <a href="{{ url_for('cost_center.list_cost_center') }}" class="btn btn-secondary">Volver a la Lista</a>
    </div>
{% endblock %}

app/templates/cost_center/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Lista de Clientes</h2>
        <a href="{{ url_for('cost_center.create_cost_center') }}" class="btn btn-primary mb-3">Crear Nuevo Centro de costo</a>
        <button class="btn btn-success mb-3" data-bs-toggle="modal" data-bs-target="#uploadModal">Cargar Excel</button>
        <a href="{{ url_for('cost_center.download_cost_centers_excel') }}" class="btn btn-outline-primary mb-3">Descargar Excel</a>
        <a href="{{ url_for('static', filename='files/centrocosto.xlsx') }}" class="btn btn-outline-secondary mb-3">Descargar Plantilla Excel
        </a>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>CC</th>
                    <th>Nombre</th>
                    <th>Gerencia</th>
                    <th>Administrador</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for cost_center in cost_centers %}
                    <tr>
                        <td>{{ cost_center.id_number }}</td>
                        <td>{{ cost_center.name }}</td>
                        <td>{{ cost_center.management }}</td>
                        <td>{{ cost_center.administrator }}</td>
                        <td>
                            <a href="{{ url_for('cost_center.cost_center_details', cost_center_id=cost_center.id) }}" class="btn btn-info">Ver Detalles</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        
    </div>
<!-- Modal para subir Excel -->
<div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="uploadModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="POST" action="{{ url_for('cost_center.upload_cost_centers') }}" enctype="multipart/form-data">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="uploadModalLabel">Subir Archivo Excel de Clientes</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
          </div>
          <div class="modal-body">
              <div class="mb-3">
                  <label for="archivo" class="form-label">Selecciona un archivo (.xlsx)</label>
                  <input type="file" class="form-control" name="archivo" id="archivo" accept=".xlsx" required>
              </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-success">Subir</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  {% endblock %}